pull_request_rules:
  - name: Automatic merge
    conditions:
      - or:
          - 'author=dependabot[bot]'
          - 'label=wait-merge'
      - -draft
      - -merged
      - -closed
      - check-success=testdata
      - check-success=build
      - check-success=test
      - check-success=codecov/patch
      - check-success=codecov/project
    actions:
      queue:
        method: squash
        name: default
  - name: Handle merged
    conditions:
      - 'label=wait-merge'
      - or:
          - merged
          - closed
    actions:
      label:
        remove: ["wait-merge"]
queue_rules:
  - name: default
    conditions:
      - check-success=testdata
      - check-success=build
      - check-success=test
      - check-success=codecov/patch
      - check-success=codecov/project
